version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: products-mongo
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGODB_DATABASE: products

  service:
    build: .
    container_name: products-service
    ports:
      - "3001:3001"
    environment:
      - MONGODBURI=mongodb://products-mongo:27017/products
      - JWTSECRET=pruebaTecnicaJWT
      - SECRETKEY=pruebaTecnica

volumes:
  mongo_data:

